---
title: 中科院软件所中文信息处理实验室预推免面试回顾
date: '2026-09-12'
date-modified: '2026-09-12'
description: 对UCAS ISCAS CIPS预推免面试的回顾。主要用于后续复习保研考核。
categories:
- interview
- math
- competitive programming
---

## 面试

面试主要问的是项目相关问题，最后问了英文问题（必定问一个，内容是项目相关的，要求不高）。
除项目问题外，还问了“你更倾向于读硕士还是博士”。

## 笔试

分为两道大题，概率题和论文阅读。

概率题是一道给定具体情境的题目，有5道小题。

情境：
软件所提供三个住宿地点（校区），A, B和C，分别能住 $a,b,c$ 名学生，一共有200名学生入学，于是在三个地点共有能容纳200人的宿舍，即 $a+b+c=200$ 。
每个学生住哪个校区的宿舍是由微信抽签（不放回采样）决定的。

- 证明抽签是公平的。第1个抽签的学生能选择所有校区，第200个学生没有选择余地，这公平吗？
- 说明随机变量的概率分布（离散的，可能是二项分布）。假设A住了80名学生，求住到B的学生数量$X$的概率分布。
- 两道具体的概率计算，似乎比较考察对实际情况的理解。本小题给出 $a,b,c$ 的具体数值。在第51位同学抽签前，老师发现前面有同学作弊，这个作弊的同学开了微信小号抽了两次签，于是老师决定他之前的两次抽签作废，让他排到最后一个再次抽签。
    - 若已知他在被发现作弊前抽到过A校区的宿舍，求他全部三次抽签覆盖全部三个校区（他A, B, C都抽到过）的概率。
    - 若已知他在被发现作弊前抽到过A,B校区其中一个的宿舍，求……（忘记了）。

论文阅读题中，给出一篇ICML的正文（不包含abstract和附录）作为参考资料，有3道小题。

- 根据正文拟定一个不超过200词的英文abstract
- 说明这篇文章的优缺点
- 拟定这篇文章后续的工作方向

## 机试

5道题，我记得的有：

- 给定两个字符串s1,s2（均为大写字母），如果s1包含s2的全部字符，且s1的对应字符数大于等于s2，那么输出Yes；否则输出No。[383. 赎金信 - 力扣](https://leetcode.cn/problems/ransom-note)
- 求字符串的最大回文子串长度。“子串”指从字符串中取任意个字符合并成的新字符串，要求维持这些字符在原字符串中的相对顺序不变。[5. 最长回文子串 - 力扣](https://leetcode.cn/problems/longest-palindromic-substring)
- 八皇后问题为背景。在无限大的棋盘上按顺序放k个皇后，然后查询“第i个皇后放上去后是否有出现冲突”，一共有q次查询。
- 字符串相关的问题，和子串有关，没太看懂。有可能是[3768. 固定长度子数组中的最小逆序对数目 - 力扣](https://leetcode.cn/problems/minimum-inversion-count-in-subarrays-of-fixed-length)

总体来讲字符串相关的问题很多，难度跨度大（从力扣简单到困难都有）。
